name: AnizottiVOTV
version: '1.0-SNAPSHOT'
main: org.cordell.anizotti.anizottiVOTV.AnizottiVOTV
api-version: '1.21'
depend: [ MenuFramework ]

commands:
  server-spawn:
    usage: "/server-spawn"
  generator-spawn:
    usage: "/generator-spawn"
  shop-spawn:
    usage: "shop-spawn"
  finder-spawn:
    usage: "/finder-spawn"
  converter-spawn:
    usage: "/converter-spawn"
  cargo-spawn:
    usage: "/cargo-spawn"
  give-money:
    usage: "/give-money"
  money:
    usage: "/money"
  status-spawn:
    usage: "/status-spawn"